title: ischool
address: No. 13 S/Crescent, Kaduna, Nigeria
email: info@itec.com
phone: 0806-169-6793
description: >- # this means to ignore newlines until "baseurl:"
  ISCHOOL is a school solution app, founded and supported by ITEC Team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: itec
github_username:  itec

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  services:
    output: true
